export const LOAD_NOTES_SUCCESS ="LOAD_NOTES_SUCCESS";
export const ADD_NOTES_SUCCESS ="ADD_NOTES_SUCCESS";
export const CURRENT_NOTES_STATE_CHANGE ="CURRENT_NOTES_STATE_CHANGE";
export const UPDATE_CURRENT_NOTE = "UPDATE_CURRENT_NOTE";
export const DElET_CURRENT_NOTE = "DElET_CURRENT_NOTE";